
CREATE TABLE IF NOT EXISTS TAREAS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    titulo VARCHAR(100) NOT NULL,
    descripcion VARCHAR(500) NOT NULL,
    etiqueta VARCHAR(100) NULL,
    venc_date TIMESTAMP NULL,
    pendiente BOOLEAN NOT NULL,
    in_progress BOOLEAN NOT NULL,
    completado BOOLEAN NOT NULL,
    archivado BOOLEAN NOT NULL,
    user_id INTEGER NOT NULL,
    FOREIGN KEY(user_id) REFERENCES USER(id)
);